// SAMPLE JSON DATA GENERATED BY CHATGPT
let products = [
    {
        "title": "Wireless Headphones",
        "image": "https://images.pexels.com/photos/374777/pexels-photo-374777.jpeg?auto=compress&cs=tinysrgb&w=600",
        "description": "High-quality wireless headphones with noise cancellation."
    },
    {
        "title": "Smart Watch",
        "image": "https://images.unsplash.com/photo-1523275335684-37898b6baf30",
        "description": "Smart fitness tracking watch with heart rate monitor."
    },
    {
        "title": "Gaming Keyboard",
        "image": "https://images.unsplash.com/photo-1517336714731-489689fd1ca8",
        "description": "RGB mechanical keyboard ideal for gaming."
    }
];


// SELECT CONTAINER
let container = document.getElementById("card-container");

// LOOP & GENERATE CARDS
products.forEach(function(item) {
    let card = `
        <div class="card">
            <img src="${item.image}" alt="Product Image">
            <h3>${item.title}</h3>
            <p>${item.description}</p>
        </div>
    `;
    container.innerHTML += card;
});
